name: Update changelog on PR merge
on:
  pull_request:
    branches:
      - main
    types: closed

jobs:
  update_changelog:
    uses: TimurTripp/action-collection/.github/workflows/update-changelog.yml@main

